# Generated by Django 2.2.3 on 2019-09-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fibonacci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Latency', models.CharField(blank=True, max_length=100, null=True)),
                ('numeric', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
